### ISSUE TITLE
gh_decode duplicates latitude as longitude

### ISSUE THREAD

**Issue by AlunHewinson** [Ironholds/geohash#1]
Even in the examples provided in the package, `gh_decode()` appears to give the wrong result for longitude:
```
gh_encode(lat = 42.60498046875, lng = -5.60302734375, precision = 5)
#[1] "ezs42"
gh_decode("ezs42")
# lat      lng      lat_error  lng_error
# 42.60498 42.60498 0.02197266 0.02197266
```
Here, `lng` should read `-5.60303` unless I've made a fundamental misunderstanding of the package.

**Comment by Ironholds** [comment]
Oh wow. What did I mess up? ;)

Thanks! I'll take a look now.

**Comment by tisotalo** [comment]
Hi, cran still has version 0.1.1 with the above bug:
https://cran.r-project.org/web/packages/geohash/index.html 

Any guidance when this could be available, or is it perhaps possible to install geohash 0.1.2 package directly from github?

**Comment by Ironholds** [comment]
It is with devtools::install_github('ironholds/geohash'), and I'll be
pushing the release up to CRAN this evening.
