### ISSUE TITLE
geohash centroid

### ISSUE THREAD

**Issue by jgilfillan** [Ironholds/geohash#10]
It would be very useful to have a function that returns the geohash centroid.

**Comment by restonslacker** [comment]
does `gh_decode()` not do what you want?  the `lat` and `lng` columns should give you the centroid.

``` r
geohash::gh_decode("bbb")
#>        lat       lng lat_error lng_error
#> 1 49.92188 -145.5469  0.703125  0.703125
```

**Comment by jgilfillan** [comment]
Ah yes, that's what I wanted.  Thanks.
