### ISSUE TITLE
More precise gh_decode()

### ISSUE THREAD

**Issue by tsai1993** [Ironholds/geohash#11]
```r
gh_decode("wx4gfbe")
       lat      lng    lat_error    lng_error
1 40.03761 116.4928 0.0006866455 0.0006866455
```

lng has only 4 digital. Can we get more precise result?

**Comment by restonslacker** [comment]
There are more digits there than R is printing to the screen. I think if
you read the help for `format` it will tell you how to display it. Sorry, I
don't have a computer handy, just my phone.  HTH

**Comment by Ironholds** [comment]
Quite! For example:

```
format(gh_decode("ezs42")[1,1], digits = 10)
[1] "42.60498047"
```
