### ISSUE TITLE
lat lng values are identical while decoding

### ISSUE THREAD

**Issue by pawangpt** [Ironholds/geohash#2]
Below is a command sequence:

gh_encode(17.37213,5.37213,6)
[1] "s55ff4"
gh_decode("s55ff4")
       lat      lng   lat_error   lng_error
1 17.37213 17.37213 0.002746582 0.005493164

I even tried with a few more geohashes but the lat-lng values were always same. I even found this in the examples quoted everywhere in the package description.

**Comment by Ironholds** [comment]
Yes; this is a bug that is fixed in the newest release, which I am throwing
up to CRAN this evening. See the other open issue.
