### ISSUE TITLE
misleading error message in gh_encode

### ISSUE THREAD

**Issue by restonslacker** [Ironholds/geohash#4]
in the example below, i attempt to get a 20 character geohash.  the error states that the default value is 6; however, as shown by the second call) no default is actually set in the r function. Asking for a  negative hash length also returns a value.  

``` r
geohash::gh_encode(1, 1, 20)
#> Warning in geohash::gh_encode(1, 1, 20): Precision must be between 1 and
#> 10. Default of 6 used.
#> [1] "s00twy"
geohash::gh_encode(1, 1)
#> Error in geohash::gh_encode(1, 1): argument "precision" is missing, with no default
geohash::gh_encode(1, 1, -1)
#> Warning in geohash::gh_encode(1, 1, -1): Precision must be between 1 and
#> 10. Default of 6 used.
#> [1] "s00twy"
```

it seems like if you are going to provide a default value for the length in some cases, it should be a default in the function call, particularly since the bounds of 1 and 10 aren't nor the default are in the `gn_encode()` docs.  Also, asking for negative values should probably throw an error since the user asked for something nonsensical.

was going to submit a PR but then realized the function is also vectorized over `precision` so i wasn't sure what you thought about handling a mix of values.  here is my proposal:

* default of 6
* `precision >=10` return length of 10 & `warning'
* `precision <1` return `NA_character_`

thoughts?

**Comment by Ironholds** [comment]
Thanks for the thoughtful bug report! It is most appreciated.

I really dislike the "invalid values? NA_character_!" paradigm: in fact, it's the thing I most loathe about R conventions, and I've deliberately tried to avoid it. We see this a lot - a good example is the distribution generators in base R. If you provide invalid options, it warns you and then generates a vector of NA_numeric_. This sucks for a variety of reasons:

1. It's not efficient. If a person went 'oh, someone submitted an invalid form, so let me spend a load of time generating 1m invalid responses, too' we'd look at them like they were wearing underwear on their heads, so why would we write code that does that same thing?
2. It's not user-friendly. Warnings are warnings; they do not stop things and they return after a function scope terminates. So this is pretty much inviting users to write code which goes out of its way to generate a load of invalid values, which it drops into a series of further function calls, which may or may not follow the same convention, which results in it eventually grinding to a halt with a totally unrelated error message and a series of confusing warnings.

So the approach I'd rather take (and will take now!) is:

1. Default of 6
2. Precision >=10 returns a length of 10 and a warning
3. Precision <1 calls stop().

**Comment by restonslacker** [comment]
Awesome. Thanks for patching this!

**Comment by Ironholds** [comment]
No problem!
